---
- hosts: all
  become: 1
  serial: 1
  tasks:
    # Update apt packages
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Reboot machine if required
    - name: reboot machine
      reboot:
        reboot_timeout: 3600
      when: reboot_required.stat.exists

- name: Send notify to Telegram
  community.general.telegram:
    token: "{{ lookup('ansible.builtin.env', 'TELEGRAM_TOKEN') }}"
    chat_id: "{{ lookup('ansible.builtin.env', 'TELEGRAM_CHAT_ID') }}"
    text: "Your precious application has been deployed: https://example.com"