---
- hosts: all
  become: 1
  serial: 1
  tasks:
    # Update apt packages
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Reboot machine if required
    - name: reboot machine
      reboot:
        reboot_timeout: 3600
      when: reboot_required.stat.exists

    # Import the telegram notification role
    - name: Notify via Telegram
      import_role:
        name: telegram_notification
      vars:
        telegram_message: "{{ inventory_hostname }} [{{ ansible_ssh_host }}] updated apt packages {{ reboot_required.stat.exists | ternary('and rebooted', '') }}"
