---
- hosts: all
  serial: 1
  tasks:
    # Update apt packages
    - name: update apt packages
      become: 1
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Reboot machine if required
    - name: reboot machine
      reboot:
        reboot_timeout: 3600
      when: reboot_required.stat.exists
