---
- hosts: all
  name: Update apt packages
  become: 1
  serial: 1
  vars:
    execution_failed: false

  tasks:
    # Update apt packages
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
      ignore_errors: yes
      register: update_apt_result
      failed_when: update_apt_result.rc != 0
      notify: set_failure_flag

    - name: Debug apt update result
      debug:
        var: update_apt_result

    # Check if reboot is required
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Import the telegram notification role
    - name: Notify via Telegram
      import_role:
        name: telegram_notification
      vars:
        execution_fail: "{{ execution_failed }}"
        telegram_message: "updated apt packages. {{ reboot_required.stat.exists | ternary('❗ NEEDS REBOOT', '✅') }}"

