---
- hosts: all
  become: 1
  serial: 1
  tasks:
    # Update apt packages
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Reboot machine if required
    - name: reboot machine
      reboot:
        reboot_timeout: 3600
      when: reboot_required.stat.exists

    - name: Basic usage
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.env', 'TELEGRAM_TOKEN') }}"

    - name: Send notify to Telegram
      community.general.telegram:
        token: "{{ lookup('ansible.builtin.env', 'TELEGRAM_TOKEN') }}"
        api_args:
          chat_id: "{{ lookup('ansible.builtin.env', 'TELEGRAM_CHAT_ID') }}"
          message_thread_id: "{{ lookup('ansible.builtin.env', 'TELEGRAM_THREAD_ID') }}"
          text: "{{ inventory_hostname }} Updated apt packages"
          parse_mode: "MarkdownV2"
