---
- hosts: all
  name: Update apt packages
  serial: 1

  tasks:
    # Update apt packages
    - name: update apt packages
      block:
        - name: update apt packages
          apt:
            upgrade: yes
            update_cache: yes
      rescue:
        # Import the telegram notification role
        - name: Notify via Telegram
          import_role:
            name: telegram_notification
          vars:
            telegram_message: >-
              {{ inventory_hostname }} [{{ ansible_ssh_host }}]:
              error

    # Check if reboot is required
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Import the telegram notification role
    - name: Notify via Telegram
      import_role:
        name: telegram_notification
      vars:
        telegram_message: >-
          {{ inventory_hostname }} [{{ ansible_ssh_host }}]:
          updated apt packages. {{ reboot_required.stat.exists | ternary('❗ NEEDS REBOOT', '✅') }}
