---
- name: Set final Telegram message based on execution status
  set_fact:
    final_telegram_message: >-
      {{ inventory_hostname }} [{{ ansible_ssh_host }}]: 
      {{ '❌ An error occurred executing {{ ansible_play_name }}. Please check the logs.' if execution_failed else telegram_message }}

- name: Send notification to Telegram
  community.general.telegram:
    token: "{{ lookup('ansible.builtin.env', 'TELEGRAM_TOKEN') }}"
    api_args:
      chat_id: "{{ lookup('ansible.builtin.env', 'TELEGRAM_CHAT_ID') }}"
      message_thread_id: "{{ lookup('ansible.builtin.env', 'TELEGRAM_THREAD_ID') }}"
      text: "{{ final_telegram_message }}"
      parse_mode: "html"
