---
- name: Send notification to Telegram
  community.general.telegram:
    token: "{{ lookup('ansible.builtin.env', 'TELEGRAM_TOKEN') }}"
    api_args:
      chat_id: "{{ lookup('ansible.builtin.env', 'TELEGRAM_CHAT_ID') }}"
      message_thread_id: "{{ lookup('ansible.builtin.env', 'TELEGRAM_THREAD_ID') }}"
      text: "{{ telegram_message }}"
      parse_mode: "html"
